// <auto-generated />
using System;
using ESTAPAR.Infrastructures.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ESTAPAR.Presentations.WebAPP.RazorPages.Migrations
{
    [DbContext(typeof(EstaparDbContext))]
    [Migration("20200712192420_InitialMigrationEstaparDbContext")]
    partial class InitialMigrationEstaparDbContext
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ESTAPAR.Core.Domain.Entities.Carro", b =>
                {
                    b.Property<int>("CarroID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Marca")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modelo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Placa")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CarroID");

                    b.ToTable("Carros");
                });

            modelBuilder.Entity("ESTAPAR.Core.Domain.Entities.Manobra", b =>
                {
                    b.Property<int>("ManobraID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CarroID")
                        .HasColumnType("int");

                    b.Property<int>("ManobristaID")
                        .HasColumnType("int");

                    b.HasKey("ManobraID");

                    b.HasIndex("CarroID");

                    b.HasIndex("ManobristaID");

                    b.ToTable("Manobras");
                });

            modelBuilder.Entity("ESTAPAR.Core.Domain.Entities.Manobrista", b =>
                {
                    b.Property<int>("ManobristaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CPF")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ManobristaID");

                    b.ToTable("Manobristas");
                });

            modelBuilder.Entity("ESTAPAR.Core.Domain.Entities.Manobra", b =>
                {
                    b.HasOne("ESTAPAR.Core.Domain.Entities.Carro", "Carro")
                        .WithMany("Manobras")
                        .HasForeignKey("CarroID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ESTAPAR.Core.Domain.Entities.Manobrista", "Manobrista")
                        .WithMany("Manobras")
                        .HasForeignKey("ManobristaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
